### PR TITLE
Support newer versions of gecode

### PR DESCRIPTION
**Pull request by thommay**

### CODE REVIEW

**Comment by thommay** [comment]
cc @markan @danielsdeleo @lamont-granquist

**Comment by danielsdeleo** [comment]
ZOMG

is it possible to get a branch in the travis matrix for this?

**Comment by thommay** [comment]
@danielsdeleo seems like yes.

**Comment by lamont-granquist** [comment]
👍

**Comment by danielsdeleo** [comment]
👍 if travis can be coaxed

**Comment by danielsdeleo** [comment]
Is it possible to make the package install a per-matrix thing?

**Comment by markan** [comment]
I'd like to hold off on this for a bit, I'm in the middle of a refactor this code.

**Comment by lamont-granquist** [comment]
i'd kind of like to go the other way around and hold off on the refactoring because we need to get this repaired in order to unblock berkshelf

**Comment by lamont-granquist** [comment]
or not...

**Comment by lamont-granquist** [comment]
@danielsdeleo it seems like a bit of a bug that we have the library installed but didn't tell it to use it, but it seems to be picking it up and exploding...

**Comment by danielsdeleo** [comment]
Probably need another squash, but woohoo! 👍

**Comment by thommay** [comment]
@markan did this better.

**Pull request closed without merging**
