### PR TITLE
Debian patches for dep_selector

### PR DESCRIPTION
**Pull request by 375gnu**
Hi, during work on debian package of dep_selector I've made several patches for it. Please review them and merge (or cherry pick) them if you satisfied with them.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @375gnu
* @boutil

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by 375gnu** [comment]
UPD: 230cb37 (Do not require dep-selector-libgecode) uses debian tools feel free to throw it away.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @boutil

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by lamont-granquist** [comment]
There's a few fundamental errors in understanding about what this package is trying to do.

Removing dep-selector-libgecode entirely defeats the whole purpose.

Similarly we can't back out setting the rpath.

We also still have to support libgecode 3.x -- although tom is working on 3.x and 4.x support in #44 

The entire point of this gem may be somewhat hostile to the packaging philosophy in debian since we don't want to use your libgecode and explicitly want to use the one we vendor in the dep-selector-libgecode gem.

And keep in mind that this gem gets installed on Debian, Ubuntu, RHEL clones, Amazon, SuSE, other Linuxen, Solaris 11/10, FreeBSD, and AIX.

The `USE_SYSTEM_GECODE=1` flag can be used to use the system libgecode, but obviously not again 4.x yet until #44 is merged.

**Pull request closed without merging**
